name: CI
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: docker.io/illuspas/xcgo:latest
    steps:
      - name: Setup go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Set up github environment variables
        uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go get -d ./...
      - name: build
        run: |
          ./darwin-build-arm64.sh
